spring:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: H2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        query.in.clause_parameter_padding: true
#server:
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
